name: lifeplan-compose

services:
  browser: 
    container_name: lifeplan-browser-container
    build: ./browser
    ports: 
      - 4000:4000

  api:
    container_name: lifeplan-api-container
    build: ./api/lifeplan
    ports:
      - "4001:8080"
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}

  database:
    image: postgres:16-alpine
    container_name: lifeplan-database-container
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
