# Docker version 26.0.0, build 2ae903e
# Docker Compose version v2.26.1-desktop.1

name: lifeplan-compose

services:
  browser: 
    container_name: lifeplan-browser-container
    build: ./browser
    ports: 
      - 4000:4000

  api:
    container_name: lifeplan-api-container
    build: ./api/lifeplan
    ports:
      - "4001:8080"
    depends_on:
      - database
    env_file:
      - ./.env

  database:
    image: postgres:16-alpine
    container_name: lifeplan-database-container
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - ./.env
    
